basePath: /api/v1
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /api/v1/projects/users/id:
    get:
      consumes:
      - application/json
      description: Health checking for the service
      operationId: CreateProject
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Health Check
      tags:
      - projects
  /api/v1/sign-in:
    post:
      consumes:
      - application/json
      description: Health checking for the service
      operationId: CreateUserByGoogle
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Health Check
      tags:
      - users
  /api/v1/sign-up:
    post:
      consumes:
      - application/json
      description: Health checking for the service
      operationId: CreateUser
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Health Check
      tags:
      - users
  /api/v1/users:
    get:
      consumes:
      - application/json
      description: Health checking for the service
      operationId: GetUser
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Health Check
      tags:
      - users
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
